browser=chrome
orange_hrm_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
herokuapp_url=https://admin:admin@the-internet.herokuapp.com/
username=Admin
password=admin123
implicitWait=2000
explicitWait=10000
MAILOSAUR_API_KEY=UalFSzJZP4VNVEvRhkwdus3P4IRVQTDf
RECIPIENT_EMAIL=anything@nlftvtj2.mailosaur.net
SENDER_EMAIL=mahendarb.reddy@gmail.com
MAILOSAUR_SERVER_ID=nlftvtj2
JIRA_USERNAME=mahendarb.reddy@gmail.com
JIRA_API_TOKEN=ATATT3xFfGF0H4O9nPHaD9etegZlepQsxSLrAltaDPDbmNv-XpzKqozdq3hjUwaB8KpokE0kbOgTI5MXMybjzMcwsw3mfKou1DI6HhZLpbGRcwmQ8hUBrNtamLV3SA65OUo_LwrX5HckgorGt5ZiiVXw1Sl_me7vfTfYXMbZQAARyPuLNEy7sVM=D6259708
JIRA_ISSUE_BASE_URI=https://mahendarbreddy.atlassian.net/rest/api
JIRA_ISSUE_PATH=/3/issue
JIRA_ISSUE_ATTACHMENT_PATH=/3/issue/{issueIdOrKey}/attachments