browser=firefox
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=Admin
password=admin123
implicitWait=2000
explicitWait=10000
MAILOSAUR_API_KEY=UalFSzJZP4VNVEvRhkwdus3P4IRVQTDf
RECIPIENT_EMAIL=anything@nlftvtj2.mailosaur.net
SENDER_EMAIL=mahendarb.reddy@gmail.com
MAILOSAUR_SERVER_ID=nlftvtj2